name: The HiFi Revival
favicon: null
layout_spectrum: 0.6913333584088832
typography_spectrum: 0.7871284836437553
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3211907227523625
  lightness: 0.1827478634659201
  saturation: 0.2840132690034807
  rhythmicContrast: 0.7993243541568518
purpose: []
