name: The HiFi Revival
favicon: null
layout_spectrum: 0.74311
typography_spectrum: 0.7871284836437553
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffe7ab'
    - '#2f2327'
    - '#d6bc89'
    - '#b4805b'
    - '#98584c'
  brandStrength: 0.3211907227523625
  lightness: 0.1827478634659201
  saturation: 0.2840132690034807
  rhythmicContrast: 0.7993243541568518
purpose: []
